profile = "user"
change-id = 135832

[llvm]
download-ci-llvm = false

[build]
host = ["x86_64-unknown-linux-gnu"]
target = ["x86_64-unknown-linux-gnu", "x86_64-unknown-oro-elf"]
extended = true
tools = ["cargo", "cargo-fmt", "clippy", "rustfmt", "analysis", "lld-wrapper"]
build-dir = "../build/rust"
verbose = 2
docs = false
compiler-docs = false
sanitizers = false

[rust]
incremental = true
download-rustc = false
description = "Experimental Rust toolchain for the Oro Operating System"
omit-git-hash = true
channel = "dev"
strip = true
optimize = 3
debug = false

[target.x86_64-unknown-linux-gnu]
llvm-config = "../build/llvm/bin/llvm-config"
llvm-has-rust-patches = false

[target.x86_64-unknown-oro-elf]
llvm-config = "../build/llvm/bin/llvm-config"
llvm-has-rust-patches = false
optimized-compiler-builtins = false
