profile = "user"
change-id = 135832

[llvm]
download-ci-llvm = false

[build]
host = ["x86_64-unknown-linux-gnu"]
target = ["x86_64-unknown-linux-gnu", "x86_64-unknown-oro-elf"]
extended = true
tools = ["cargo", "cargo-fmt", "clippy", "rustfmt", "analysis", "lld-wrapper"]
build-dir = "/home/runner/oro-toolchain/rust"

[rust]
incremental = true
download-rustc = false
description = "Experimental Rust toolchain for the Oro Operating System"
omit-git-hash = true

[target.x86_64-unknown-oro-elf]
llvm-config = "/home/runner/oro-toolchain/llvm/bin/llvm-config"
llvm-has-rust-patches = false
optimized-compiler-builtins = false